function [Data, Index] = initial_data(M, L_block)
%% the theta
i = 1 : M;
Theta = 2 * pi .* (i - 1) ./ M;

%% generate data symbols and corresponding index
Index = randi(M, L_block, 2); % the index of data, which are generated by random numbers
Data = zeros(L_block, 2);
for k = 1 : L_block
    Data(k,:) = [exp(1i* Theta(Index(k, 1))), exp(1i* Theta(Index(k, 2)))];
end

Data = Data * sqrt(1/2);
end


